In [1]:
import numpy as np


In [2]:
np1 = np.array([1,2,3,4,5])

In [3]:
np1

array([1, 2, 3, 4, 5])

In [4]:
type(np1)

numpy.ndarray

In [6]:
Mat1 = np.array([[1,2],[3,4]])

In [7]:
Mat1

array([[1, 2],
       [3, 4]])

In [9]:
np1.shape


(5,)

In [10]:
Mat1.shape

(2, 2)

In [11]:
Mat1.dtype

dtype('int32')

In [13]:
mat2 = np.arange(0,4,1)

In [14]:
mat2

array([0, 1, 2, 3])

In [15]:
mat3 = np.linspace(0,10,20)

In [16]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])